ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/include
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera-pp
