#
# Makefile for grip sensors
#

obj-$(CONFIG_SENSORS_SX9360)  		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9360_SUB)	+= sx9360_sub.o
obj-$(CONFIG_SENSORS_SX9364)		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9364_SUB)	+= sx9360_sub.o
obj-$(CONFIG_SENSORS_SX9364_SUB2)	+= sx9360_sub2.o
obj-$(CONFIG_SENSORS_ISG5320A)		+= isg5320a.o
obj-$(CONFIG_SENSORS_ISG5320A_SUB)	+= isg5320a_sub.o
