# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)		+= exynos_devfreq.o
exynos_devfreq-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o governor_simpleinteractive.o
exynos_devfreq-$(CONFIG_EXYNOS_ALT_DVFS)	+= exynos-ppc.o
