#
# Exynos CPU Performance Profiling
#

# Exynos CPU Performance
obj-$(CONFIG_EXYNOS_PERF)	+= exynos_perf.o
exynos_perf-y			+= exynos_perf_main.o exynos_perf_cpu.o exynos_perf_cpufreq.o
exynos_perf-y			+= exynos_perf_cpuidle.o exynos_perf_ncmemcpy_simple.o
exynos_perf-y			+= exynos_perf_gmc.o
