#obj-$(CONFIG_BCM_GPS_TTY_DRIVER) += bcm_gps_tty.o
#obj-$(CONFIG_BCM_GPS_I2C_DRIVER) += bcm_gps_i2c.o
#obj-m += bcm_gps_spi.o
#obj-y += bcm_gps_regs.o
#obj-y += bcm_gps_mem.o
#obj-$(CONFIG_BCM_GPS_HOSTWAKE_DRIVER) += bcm_gps_hostwake.o
#obj-y += bbd_rpc_lh.o bbd.o
