obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += api/

ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/include
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/interface
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/hardware
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/hardware/api
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/vendor
