obj-$(CONFIG_EXYNOS_PABLO_ISP) += is-v8_1_0/
obj-$(CONFIG_EXYNOS_PABLO_ISP) += is-v8_10_0/
obj-$(CONFIG_EXYNOS_PABLO_ISP) += is-v8_20_0/
obj-$(CONFIG_EXYNOS_PABLO_ISP) += is-v9_1_0/

EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/include
