EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/hardware
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/vendor
