#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#
obj-$(CONFIG_SEC_DISPLAYPORT_EXT_FUNCTION)		+= dp_ext_func.o
dp_ext_func-$(CONFIG_SEC_DISPLAYPORT_LOGGER)	+= dp_logger.o
dp_ext_func-$(CONFIG_SEC_DISPLAYPORT_BIGDATA)	+= displayport_bigdata.o
dp_ext_func-$(CONFIG_SEC_DISPLAYPORT_SELFTEST)	+= dp_self_test.o
