obj-$(CONFIG_CAMERA_LASER_AF_VL53L5_OBJ) += is-laser-af-vl53l5.o

EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/sensor
