obj-$(CONFIG_VIDEO_EXYNOS_REPEATER)				+= repeater/
obj-$(CONFIG_VIDEO_EXYNOS_TSMUX)				+= tsmux/
obj-$(CONFIG_VIDEO_EXYNOS_MFC)					+= mfc/
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS)			+= camera-pp/
obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP)				+= camera/
obj-$(CONFIG_VIDEO_EXYNOS_JPEG_SQZ)				+= jsqz/
obj-$(CONFIG_VIDEO_EXYNOS_MC_FRC)				+= mcfrc/
EXTRA_CLAGS += -Idrivers/media/video
