#
# Makefile for ACPM.
#

obj-$(CONFIG_EXYNOS_ACPM)    += exynos_acpm.o 
exynos_acpm-$(CONFIG_EXYNOS_ACPM)    += acpm.o acpm_ipc.o
exynos_acpm-$(CONFIG_EXYNOS_ACPM_MFD)	+= acpm_mfd.o
obj-$(CONFIG_EXYNOS_ACPM_S2D)	+= acpm_s2d.o
obj-$(CONFIG_EXYNOS_ACPM_PLGDBG)	+= plugin_dbg.o
