#
# Copyright (c) 2020 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_PD_MGR)	+= camerapp-pd-mgr.o

ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera-pp/
ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/include
